import Link from "next/link";
import {
  ArrowRight,
  BadgeCheck,
  Braces,
  Calculator,
  ChartNoAxesCombined,
  Equal,
  FileCheck2,
  FunctionSquare,
  Grid3X3,
  ShieldCheck,
} from "lucide-react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";

const tools = [
  { name: "Differentiate", api: "differentiate", example: "What is the derivative of x^2 sin(x)?", output: "Symbolic derivative + graph", icon: FunctionSquare },
  { name: "Integrate", api: "integrate_expression", example: "Integrate x^2 from 0 to 3", output: "Exact integral + area graph", icon: Braces },
  { name: "Solve equations", api: "solve_equation", example: "Solve x^2 - 5x + 6 = 0", output: "Exact and numeric roots", icon: Equal },
  { name: "Simplify / factor", api: "simplify_expression", example: "Factor x^3 - x", output: "Equivalent symbolic form", icon: Braces },
  { name: "Evaluate", api: "evaluate_expression", example: "What is Sin[Pi/6]?", output: "Exact and numeric value", icon: Calculator },
  { name: "Plot", api: "plot_function", example: "Plot sin(x)/x", output: "Wolfram-rendered graph", icon: ChartNoAxesCombined },
  { name: "Check answers", api: "verify_answer", example: "What is the derivative of x^3?", output: "Symbolic equivalence loop", icon: BadgeCheck },
  { name: "Matrix analysis", api: "matrix_analysis", example: "Eigenvalues of {{2, 1}, {1, 2}}", output: "Rank, determinant, eigenvalues, inverse", icon: Grid3X3 },
];

const contract = [
  ["Result", "Computed by Wolfram Language", "Verified"],
  ["Graph", "Rendered by Wolfram Language", "Verified"],
  ["Student answer check", "Symbolically compared by Wolfram", "Verified"],
  ["Numeric narration claims", "Checked against results and inputs", "Guarded"],
  ["Explanation wording", "Generated by Gemini around computed values", "Not formally proven"],
  ["AI-alone answer", "Gemini without tools, shown as a baseline", "Unchecked"],
];

export default function CapabilitiesPage() {
  return (
    <div className="app-frame flex min-h-screen flex-col">
      <SiteHeader active="capabilities" />
      <main className="mx-auto w-full max-w-[1340px] flex-1 px-3 py-6 sm:px-5 lg:px-8 lg:py-10">
        <section className="grid gap-6 border-b border-line pb-8 lg:grid-cols-[minmax(0,1fr)_390px] lg:items-end">
          <div>
            <div className="eyebrow text-[var(--color-verify)]">Tool lab / supported computation</div>
            <h1 className="mt-3 max-w-4xl text-3xl font-bold leading-[1.12] text-text sm:text-5xl">
              Eight approved tools. <span className="text-[var(--color-verify)]">One visible contract.</span>
            </h1>
            <p className="mt-4 max-w-3xl text-sm leading-7 text-muted">
              Explore the exact math operations StepWise supports, then launch any example into the live tutor. Each tool runs a vetted Wolfram Language template with a 15-second compute limit.
            </p>
          </div>
          <div className="panel">
            <div className="panel-header">
              <span className="flex items-center gap-2 text-xs font-bold uppercase text-text"><ShieldCheck size={14} className="text-[var(--color-verify)]" /> Execution boundary</span>
              <span className="status-chip status-chip-accent">Math-only</span>
            </div>
            <div className="p-4 text-xs leading-6 text-muted">
              Inputs pass an allowlist before execution. Assignments, file access, arbitrary functions, and executable syntax are rejected.
            </div>
          </div>
        </section>

        <section className="mt-6 panel">
          <div className="panel-header">
            <div>
              <div className="eyebrow">Live capability catalog</div>
              <div className="mt-1 text-sm font-bold text-text">Select an example to run it in the tutor</div>
            </div>
            <span className="status-chip status-chip-accent">08 tools</span>
          </div>
          <div className="grid gap-px bg-line md:grid-cols-2 xl:grid-cols-4">
            {tools.map((tool, index) => {
              const Icon = tool.icon;
              return (
                <article key={tool.api} className="flex min-h-64 flex-col bg-[var(--color-surface)] p-4">
                  <div className="flex items-start justify-between gap-3">
                    <span className="step-index step-index-active">{String(index + 1).padStart(2, "0")}</span>
                    <Icon size={16} className="text-[var(--color-verify)]" />
                  </div>
                  <h2 className="mt-4 text-sm font-bold text-text">{tool.name}</h2>
                  <div className="mt-1 font-mono text-[9px] uppercase text-faint">{tool.api}</div>
                  <p className="mt-4 flex-1 text-xs leading-6 text-muted">{tool.output}</p>
                  <div className="mt-4 border-l-2 border-[var(--color-verify)] bg-[#fff3ed] px-3 py-2 text-xs leading-5 text-muted">
                    {tool.example}
                  </div>
                  <Link
                    href={`/?question=${encodeURIComponent(tool.example)}`}
                    className="console-action console-action-primary mt-3 w-full"
                  >
                    Run in tutor <ArrowRight size={13} />
                  </Link>
                </article>
              );
            })}
          </div>
        </section>

        <section className="mt-6 grid items-start gap-4 lg:grid-cols-[1.15fr_0.85fr]">
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="eyebrow">Honest verification matrix</div>
                <div className="mt-1 text-sm font-bold text-text">What the product does and does not prove</div>
              </div>
              <FileCheck2 size={15} className="text-[var(--color-verify)]" />
            </div>
            <div className="grid gap-px bg-line">
              {contract.map(([item, method, status]) => (
                <div key={item} className="grid gap-2 bg-[var(--color-surface)] px-4 py-3 sm:grid-cols-[0.8fr_1.4fr_auto] sm:items-center">
                  <div className="text-xs font-bold text-text">{item}</div>
                  <div className="text-xs leading-5 text-muted">{method}</div>
                  <span className={`status-chip ${status === "Unchecked" ? "" : "status-chip-accent"}`}>{status}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="panel">
            <div className="panel-header">
              <div className="eyebrow">Deliberate scope</div>
              <span className="status-chip">MVP</span>
            </div>
            <div className="space-y-4 p-4 text-xs leading-6 text-muted">
              <p>StepWise is intentionally a focused math tutor, not a general chatbot or universal STEM solver.</p>
              <p>The approved-tool boundary makes the computation inspectable and keeps untrusted text away from arbitrary Wolfram execution.</p>
              <Link href="/architecture" className="console-action w-full">Inspect architecture <ArrowRight size={13} /></Link>
            </div>
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
